name: Watermelon Test Execution

on:
  workflow_dispatch:

jobs:

  execute-tests:

    runs-on: windows-latest

    env:

      WM_USERNAME: ${{ secrets.WM_USERNAME }}
      WM_PASSWORD: ${{ secrets.WM_PASSWORD }}

      AUTH_PROVIDER_URL: https://wm-sandbox-auth-1.watermelon.us/realms/watermelon/protocol/openid-connect/token

      EXECUTE_API_URL: https://wm-sandbox-1.watermelon.us/services/wmuitestcontroller/api/test-packs/execute_v2

      STATUS_API_URL: https://wm-sandbox-1.watermelon.us/services/wmuitestcontroller/api/test-runs

      PACK_ID: "9024760"
      ENVIRONMENT_ID: "8890901"
      BUILD_ID: "8902051"
      WEB_AUT_ID: "9049052"

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate
        id: auth
        shell: pwsh
        run: |

          $body = @{
            client_id  = "web_app"
            username   = $env:WM_USERNAME
            password   = $env:WM_PASSWORD
            grant_type = "password"
          }

          $response = Invoke-RestMethod `
            -Method POST `
            -Uri $env:AUTH_PROVIDER_URL `
            -ContentType "application/x-www-form-urlencoded" `
            -Body $body

          echo "wm_token=$($response.access_token)" >> $env:GITHUB_OUTPUT

      - name: Execute Test Pack
        id: execute
        shell: pwsh
        run: |

          $token = "${{ steps.auth.outputs.wm_token }}"

          $payload = @{
            packId = [int]$env:PACK_ID
            runNow = $true
            environmentId = [int]$env:ENVIRONMENT_ID
            buildId = [int]$env:BUILD_ID
            iteration = 1
            headlessExecution = $false
            webAutId = [int]$env:WEB_AUT_ID
          } | ConvertTo-Json

          $response = Invoke-RestMethod `
            -Method PUT `
            -Uri $env:EXECUTE_API_URL `
            -Headers @{
              Authorization = "Bearer $token"
            } `
            -ContentType "application/json" `
            -Body $payload

          Write-Host "RUN ID: $($response.id)"

          echo "run_id=$($response.id)" >> $env:GITHUB_OUTPUT

      - name: Monitor Execution
        shell: pwsh
        run: |

          $token = "${{ steps.auth.outputs.wm_token }}"
          $runId = "${{ steps.execute.outputs.run_id }}"

          do {

            Start-Sleep -Seconds 10

            $result = Invoke-RestMethod `
              -Method GET `
              -Uri "$($env:STATUS_API_URL)/$runId" `
              -Headers @{
                Authorization = "Bearer $token"
              }

            Write-Host "STATE: $($result.state)"
            Write-Host "STATUS: $($result.status)"

          } while ($result.state -ne "COMPLETED")

          if ($result.status -eq "FAIL") {
            throw "Watermelon execution failed"
          }

          Write-Host "Watermelon execution completed successfully"
